name: convenia_mobile
description: "Convenia — Antes de comprar, elige dónde. App móvil de comparación de precios entre supermercados."
publish_to: "none"
version: 3.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  google_fonts: ^7.0.0
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.2
  path_provider: ^2.1.6
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
